### PR TITLE
fix unable to fetch URIs with gpg keys

### PR DESCRIPTION
**Pull request by sisivy**

### CODE REVIEW

**Comment by CodingFabian** [comment]
Is this referring to a problem like https://unix.stackexchange.com/a/507581, where apt-key cannot deal with a proxy server, but curl can?

**Comment by sisivy** [comment]
Hi Fabian, yes. But in environment without proxies I've got also an error. curl fixed both..

**Comment by CodingFabian** [comment]
LGTM, I leave the merge decision to @sigil66

**Comment by mdonkers** [comment]
Closing as we have fully refactored the `Dockerfile`s and don't use APT anymore.
Please open a new PR if still relevant.

**Pull request closed without merging**
