### PR TITLE
Add THIRD_PARTY file

### PR DESCRIPTION
**Pull request by mmanciop**

### CODE REVIEW

**Comment by mmanciop** [comment]
@CodingFabian absolutely. The requirements for Google Cloud Marketplace however are not realized right away my the Maven License plugin, because Google requires us to copy the letter of the license in the third-party file. The plugin will need some massaging and, as additional metadata, a mapping from GAV to license file and probably validation that all files are there. I'd estimate 2 days of dev time to make such a file.

This PR is just a stop-gap for Google Marketplace.

**Comment by CodingFabian** [comment]
just want to make sure we get it automated, because this file is effectively outdated already

**Comment by mmanciop** [comment]
@CodingFabian agreed. I'll put stuff in PivotalTracker for it. I guess it is an agent topic.

**Comment by mmanciop** [comment]
Also, I wanna give another pass to the text file. There are some Apache 2.0 files that had been modified by the projects and I wanna reflect them for good measure.

**Comment by mmanciop** [comment]
OK, now the file is good. **IMPRIMATUR**

**Pull request merged**
