### PR TITLE
Go template cleanup

### PR DESCRIPTION
**Pull request by doertedev**
Ready for review, still testing this.

### CODE REVIEW

**Comment by doertedev** [comment]
g2g

**Comment by mdonkers** [comment]
Note that these settings are not yet included:
https://github.com/instana/docs/pull/639/files#diff-190fcb86982299e88730e9dfdf858661R38
Previous PR was merged before someone could add them. @doertedev Can you add to this PR? Or not needed anymore and needs to be removed from docs?

**Comment by doertedev** [comment]
See https://github.com/instana/docs/pull/639/files#issuecomment-524769553 - this will have to be adjusted first @mdonkers @mmanciop - one host var where there need to be two separate urls for shared and features.

**Comment by mdonkers** [comment]
Stale, closing

**Pull request closed without merging**
